# -*- coding: utf-8 -*-
"""Programming Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bu-y5HNmcUmVB3S6xHchM-khna-sxMrl
"""

print("Welcome to the Global Electricity Bill Calculator!")


acc_num=input("Enter account number: ")
month=input("Enter month (e.g., January, February, etc.): ")
elec_plan=input("Enter electricity plan (EFIR or EFLR): ")
elec_used=float(input("Enter electricity used in (in kWh): " ))
gas_plan=input("Enter gas plan (GFIR or GFLR)) ")
gas_used=float(input("Enter gas used (in GJ): "))
prov=input("Enter province of residence (two letters): ")

elec_cost = 0  # Initialize electricity cost
gas_cost = 0   # Initialize gas cost
prov_tax_rate = 0  # Initialize provincial tax rate

# Electricity Fixed Rate (EFIR)
if elec_plan == "EFIR":
  # Price of kWh = 8.36 (cents)/kWh for the first 1000 kWh -- guaranteed 4 years
  if elec_used <= 1000:
    elec_cost = elec_used * 8.36 / 100
  # Price of kWh = 9.41 (cents)/kWh AFTER 1000 kWh
  else:
    elec_cost = 1000 * 8.36 / 100 + (elec_used - 1000) * 9.41 / 100
# Electricity Floating Rate (EFLR)
elif elec_plan == "EFLR":
  # Price of kWh = 9.11 (cents)/kWh
  elec_cost = elec_used * 9.11 / 100


# Gas Fixed Rate (GFIR)
if gas_plan == "GFIR":
  # Price of kWh = 4.56 (cents)/GJ for the first 950 GJ -- guaranteed 4 years
  if gas_used <= 950:
    gas_cost = gas_used * 4.56 / 100
  # Price of kWh = 5.89 (cents)/GJ AFTER 950 GJ
  else:
    gas_cost = 950 * 4.56 / 100 + (gas_used - 950) * 5.89 / 100
# Gas Floating Rate (GFLR)
elif gas_plan == "GFLR":
  # Price of kWh = 3.93 (cents)/GJ
  gas_cost = gas_used * 3.93 / 100


# Province Sales Tax Rate
if prov in ("AB", "BC", "MB", "NT", "NU", "QC", "SK", "YT"):
  # 5% Tax Rate
  prov_tax_rate = 0.05
elif prov == "ON":
  # 13% Tax Rate
  prov_tax_rate = 0.13
else:
  # 15% Tax Rate (NB, NL, NS)
  prov_tax_rate = 0.15


month_fee=120.62
gas_fee=1.32

# Calculate subtotal before tax
subtotal = elec_cost + gas_cost + gas_fee + month_fee

# Calculate provincial tax
prov_tax = subtotal * prov_tax_rate

# Amount Due
amount_due = (int((subtotal + prov_tax) * 100)) / 100.0 # Add the provincial tax to the subtotal
print("Thank you! Your total amount due now is:", amount_due, "CAD")